package ru.goryachev.multichief.construction.repository;

import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.annotation.Rollback;
import ru.goryachev.multichief.construction.app.AppWebInit;
import ru.goryachev.multichief.construction.model.entity.Eir;

import java.util.List;
import java.util.Optional;

/**
 * CRUD JPA Repository testing with real DB.
 * Necessary to use Lifecycle.PER_CLASS (@TestInstance) to work with common id (testId variable is end-to-end id).
 * An entity with autogenerated ID suppose to be created in the first method (1).
 * The ID will be used in each method (2,4,5).
 * The entity with ID suppose to be deleted in the last one (5).
 * Setting WebEnvironment.NONE does not start the embedded servlet container (MultiChief does not use embedded).
 * @author Lev Goryachev
 * @version 1.0
 */

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
@SpringBootTest(classes = AppWebInit.class, webEnvironment = SpringBootTest.WebEnvironment.NONE)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class EirRepositoryTest {

    Long testId;

    @Autowired
    private EirRepository eirRepository;

    @Test
    @Order(1)
    @Rollback(value = false)
    public void saveEirTest(){
        Eir eir = new Eir();
        eir.setEirCodeNumber("testValueAbc");
        eir.setEirDescription("testValueDef");
        eir.setLink("testValueXyz");

        Eir savedEir = eirRepository.save(eir);
        this.testId = savedEir.getId();
        Assertions.assertThat(savedEir.getId()).isGreaterThan(0);
    }

    @Test
    @Order(2)
    public void getEirTest(){
        Eir eir = eirRepository.findById(testId).get();
        Assertions.assertThat(eir.getId()).isEqualTo(testId);
    }

    @Test
    @Order(3)
    public void getAllEirsTest(){
        List<Eir> eirs = eirRepository.findAll();
        Assertions.assertThat(eirs.size()).isGreaterThan(0);
    }

    @Test
    @Order(4)
    @Rollback(value = false)
    public void updateEirTest(){
        Eir eir = eirRepository.findById(testId).get();
        eir.setEirCodeNumber("testValueChanged");
        Eir eirUpdated =  eirRepository.save(eir);
        Assertions.assertThat(eirUpdated.getEirCodeNumber()).isEqualTo("testValueChanged");
    }

    @Test
    @Order(5)
    @Rollback(value = false)
    public void deleteEirTest(){

        Eir eir = eirRepository.findById(testId).get();
        eirRepository.delete(eir);

        //eirRepo.deleteById(1L);

        Eir eirEmpty = null;
        Optional<Eir> optionalEir = eirRepository.findById(testId);
        if(optionalEir.isPresent()){
            eirEmpty = optionalEir.get();
        }
        Assertions.assertThat(eirEmpty).isNull();
    }
}